customhost = "employee.cfi9rvp5miwn.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "jackcokwanwaishing-employee"
customregion = "us-east-1"
